### ISSUE TITLE
Huge problems with TFA Base

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [Zet0rz/nzombies#374] opened 2017-02-11 19:46 UTC
I have two huge problems with weapons on TFA Base when using latest version of nZombies:
~1. Can't damage zombies when downed. I see blood particles coming from zombies, but no damage are dealt to them.~ EDIT: this problem somehow fixed itself ¯\\\_(ツ)\_/¯
2. Can't use any weapon on TFA Base as special weapon. I register them, but when i try to use them, they just playing holster animation. (you can see on [this video](https://www.youtube.com/watch?v=3OgiSj0LdnY) that this happens only with weapons on TFA Base)

**Comment by minin43** [comment] 2017-02-11 22:21
Your avatar is from a porn comic.

**Comment by Zet0rz** [comment] 2017-02-11 23:30
Interesting. Thanks for pointing out! Next update brings TFA support, so I'll be sure to make this work for that! For testing purposes, can you send me the melee weapon addons so I can use the same ones along with the code you used to register them?

**Comment by YuRaNnNzZZ** [comment] 2017-02-12 00:23
- [Pack with melees on TFA Base](http://steamcommunity.com/sharedfiles/filedetails/?id=712848264)
- [Half-Life 2 Melee Pack](https://steamcommunity.com/sharedfiles/filedetails/?id=675824914) (this one works)
- [Code I used to register them as special weapons](https://gist.github.com/YuRaNnNzZZ/6ad2bd5b3ea63ea7a083f39e849aa8db)

**Comment by YuRaNnNzZZ** [comment] 2017-02-12 10:39
Found another problem: an error pops out when i reload weapon with Speed Cola perk:
```
[ERROR] addons/nzombies/gamemodes/nzombies/gamemode/weapons/sh_wep_modifiers.lua:117: attempt to call method 'SetReloadingEnd' (a nil value)
  1. Reload - addons/nzombies/gamemodes/nzombies/gamemode/weapons/sh_wep_modifiers.lua:117
   2. value - lua/weapons/tfa_doom_ssg/shared.lua:106
    3. ProcessEvents - lua/weapons/tfa_gun_base/sh_events.lua:61
     4. Think2 - lua/weapons/tfa_gun_base/shared.lua:579
      5. Think2 - lua/weapons/tfa_bash_base/shared.lua:230
       6. PlayerThink - lua/weapons/tfa_gun_base/shared.lua:538
        7. v - lua/tfa/modules/tfa_hooks.lua:15
         8. unknown - lua/includes/modules/hook.lua:84
```
However, weapon itself reloads fine and it's just annoying error that pops out on every reload.

**Comment by YuRaNnNzZZ** [comment] 2017-02-12 11:57
And i found another bug, this time with weapons using custom ammo, like [Gauss](http://steamcommunity.com/sharedfiles/filedetails/?id=854972559) with `doom_plasma` ammo type or Eviscerator from [KF2 Melees pack](https://steamcommunity.com/sharedfiles/filedetails/?id=848490709) with `eviscerator_blades`.
When i equip the weapon, it's ammo counter resets to -10, so i just can't shoot.

**Comment by Zet0rz** [comment] 2017-02-12 23:33
> Found another problem: an error pops out when i reload weapon with Speed Cola perk:

This was fixed in my changes in the upcoming update. Thanks for the rest of the information, it really helps me test and fix when I know exactly what needs testing!

**Comment by Zet0rz** [comment] 2017-02-13 16:08
The Gauss and Eviscerator weapons work normally for me, I get ammo for them and max ammo also works. They don't draw ammo on the HUD though, will try to make them do that

The melee weapons have been fixed now

**Comment by Zet0rz** [comment] 2017-02-13 16:56
Nevermind, there was a bug in ammo types - It's because max ammo was given before the weapon's ammo was changed, then it changed. It should work now, although in a slightly hacky way since I just delayed when ammo is given by 1 tick. You'll quickly see a fake number, then it sets the right amount.

There are more bugs related to ammo than just that, stuff including PaP and ammo you automatically get on spawn. Maybe I should revamp the ammo system again in some way so that ammo is instantly replaced/default ammo is given to the new ammo type.

**Comment by YuRaNnNzZZ** [comment] 2017-03-01 17:44
Well, now after update, weapons with custom ammotypes works.
~~BUT! They now have infinite ammo.~~
Looks like now every gun got infinite ammo. (at least every gun on TFA Base)

**Comment by Zet0rz** [comment] 2017-03-01 18:19
Every gun got infinite ammo? I just shot some random weapons, including some TFA ones, they weren't infinite? Any specific guns you can tell me you know for sure does this?

**Comment by YuRaNnNzZZ** [comment] 2017-03-01 18:24
I've tested it with M1911 from [CS:O Pack](https://steamcommunity.com/sharedfiles/filedetails/?id=712848264), AK-47 from [GS:GO Pack](http://steamcommunity.com/workshop/filedetails/?id=533104097), [Ravager](http://steamcommunity.com/sharedfiles/filedetails/?id=841791181) and [Gauss](http://steamcommunity.com/sharedfiles/filedetails/?id=854972559).

Also melees work, but special grenades not working at all.

**Comment by Zet0rz** [comment] 2017-03-01 18:36
Oh right, only tested with the melees when I did this. Will put grenades on the todo list! I also used the Ravager and its ammo worked normally as seen here: https://youtu.be/ItvSSP2pnXg?t=16s

**Comment by ghost** [comment] 2017-03-01 18:53
No worries here, it's on my side; the ammo counter itself was broken, not the ammo consumption.  I encourage both of you to test with the latest patch.

**Comment by YuRaNnNzZZ** [comment] 2017-03-01 19:13
Yeah, can confirm, infinite ammo is not an issue anymore.

**Comment by Zet0rz** [comment] 2017-03-21 14:43
Confirmed grenades also work. You had the holster time (last number) set so short, that the PrimaryAttack function didn't have time to actually throw the grenade.

**Closed as completed by Zet0rz** 2017-03-21 14:43 UTC
