### ISSUE TITLE
Collision with player with bullet and after respawn from dead.

### ISSUE THREAD

**Issue by Terrible1337** [Zet0rz/nzombies#203] opened 2016-05-19 18:31 UTC
Bullet Collision is annoying for us i should set to shouldcollide but how so?

Also, player has been re-spawn after next round its bug with collision player can make stuck on other the player so sigh.

Edit: I can't use "PaP" Punch A Pack no idea what happens since this update.

**Comment by Zet0rz** [comment] 2016-05-19 20:01
Bullet collision? With what? Players colliding with players?

I didn't get the second thing? What bug?

And thanks for pointing out the PaP issue. Fixed.

**Comment by Terrible1337** [comment] 2016-05-19 20:15
1. When player is front of me so i can't shot through the player so well.
2. 2nd Players is respawn then 2nd players collision is very solid like 1st player can't through the 2nd players.

Edit: Speed Cola is bug, won't get you fast reload the ammo clip is delay but animation is correctly.
Edit2: After PaP, when you have big than currently clip ammo wont be reload animation but ammoclip is works itself without animation.

**Comment by Zet0rz** [comment] 2016-05-20 18:41
> Edit: Speed Cola is bug, won't get you fast reload the ammo clip is delay but animation is correctly

Speed Cola works normally on FAS2, CW2, and M9K weapons. CW2 and FAS2 get special treatment, but M9K is handled like any generic gun, meaning it should work for all.

> Edit2: After PaP, when you have big than currently clip ammo wont be reload animation but ammoclip is works itself without animation.

What weapon pack? Confirmed working normally on all the same ones as tested with above.

> When player is front of me so i can't shot through the player so well.

Made bullets go through players. Change will be part of next update.

> 2nd Players is respawn then 2nd players collision is very solid like 1st player can't through the 2nd players.

This is likely because of the team being set to spectator when dying but not reset when respawning. This has also been changed and will be in the next update.

**Comment by Terrible1337** [comment] 2016-05-21 00:56
Well, I'm using a CW 2.0 so nvm its works sorry.

There is bug with replace gun, when you bought the 2nd gun then use your primary weapon then buy from the box or wall so they won't let replace your 1st gun.

**Comment by Zet0rz** [comment] 2016-05-22 16:09
> There is bug with replace gun, when you bought the 2nd gun then use your primary weapon then buy from the box or wall so they won't let replace your 1st gun

That seems to be the same bug as listed in #206. Closing this one, continuing that problem in that issue.

**Closed as completed by Zet0rz** 2016-05-22 16:09 UTC

**Comment by Zet0rz** [comment] 2016-05-24 19:42
Commit 288ec9da64e47223ba8307ec8787f853f620298c makes bullets go through players as well as sets the players' teams to TEAM_PLAYER on respawn, which was likely the cause of the collision. Can you confirm working?
